import Head from 'next/head';
import { Heading, Flex, Stack } from '@chakra-ui/react';
import Card from '../components/Card';

export default function Home() {
	return (
		<Stack as="container">
			<Head>
				<title>Delman Internship</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Flex
				as="main"
				alignItems="center"
				justifyContent="center"
				flexDirection="column"
				height="100vh"
			>
				<Flex>
					<Heading as="h1" size="xl" m="2">
						Internship Program
					</Heading>
				</Flex>

				<Flex alignItems="center" justifyContent="center" mt="20px">
					<Card
						title="Title Transformer"
						desciprition="A simple title transformation panel"
						link="/title-transformer"
					/>

					<Card
						title="User Fetcher"
						desciprition="A simple API fetching and rendering process"
						link="/user-fetcher"
					/>
				</Flex>
			</Flex>
		</Stack>
	);
}
